include: package:lints/recommended.yaml

linter:
  rules:
    - camel_case_types
    - constant_identifier_names
    - prefer_final_locals
    - prefer_final_in_for_each
    - always_declare_return_types
    - prefer_single_quotes
    - sort_child_properties_last
    - unawaited_futures
    - unsafe_html
