name: dart_openapi_codegen
description: Generate dart client code for OpenAPI specifications
version: 0.1.0
repository: https://github.com/famedly/dart_openapi_codegen

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.19.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.1
