name: dart_openapi_codegen
description: Generate dart client code for OpenAPI specifications
version: 0.1.0
repository: https://gitlab.com/famedly/dart_openapi_codegen

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  yaml: ^3.1.0

dev_dependencies:
  pedantic: ^1.9.0
